# Generated by Django 3.1 on 2020-09-14 00:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0003_delete_prueba'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAsistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=150, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('requisitos', models.FileField(blank=True, upload_to='requisitos')),
                ('fecha_inicio', models.DateField(default=datetime.date.today)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('tipo_asistencias', models.ManyToManyField(to='programa.TipoAsistencia')),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionBeneficio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateTimeField(default=datetime.datetime.today)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=8)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.persona')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programa.programa')),
                ('tipo_asistencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programa.tipoasistencia')),
            ],
        ),
    ]
