# Generated by Django 3.1 on 2020-11-17 23:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionbeneficio',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asignacionbeneficio',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
