# Generated by Django 3.1 on 2021-09-30 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionbeneficio',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_beneficios', to='programa.programa'),
        ),
    ]
