# Generated by Django 3.1 on 2021-10-20 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0002_auto_20201117_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
