# Generated by Django 3.1 on 2021-10-20 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0004_creacion_valor_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
    ]
