# Generated by Django 3.1 on 2020-09-13 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_prueba'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prueba',
        ),
    ]
