# Generated by Django 3.1 on 2021-09-29 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_delete_prueba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadosalud',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estado_salud', to='persona.persona'),
        ),
    ]
