# Generated by Django 3.1 on 2022-10-17 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_delete_prueba'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadosalud',
            options={'verbose_name_plural': 'Estados de Salud'},
        ),
    ]
